Задание 1_1_1
MZolot/OOP pull request #1
Opened 2021-09-26 16:18 UTC by MZolot

2021-09-29 17:34 UTC, molo4evan commented
Что-то не вижу файлов gradle... Ты точно создала gradle-проект, а не просто Java-проект? В IDEA `New -> Project -> Gralde (в меню слева)`

2021-09-29 17:43 UTC, molo4evan requested changes

2021-09-29 17:43 UTC, molo4evan commented on Task_1_1_1/src/main/java/nsu/oop/HeapSort.java
> +        k = n;
Стоит назвать поле более осмысленно, `k = n` не несет особой смысловой нагрузки

2021-09-29 17:43 UTC, molo4evan commented on Task_1_1_1/src/main/java/nsu/oop/HeapSort.java
> +        if (k == 0 || heap[(k0)] < heap[k] ) {
А скобочки зачем?

`(k0)`

2021-09-29 17:43 UTC, molo4evan commented on Task_1_1_1/src/main/java/nsu/oop/HeapSort.java
> +            heap[i] = arr[i];
Можно же сделать без выделения дополнительной памяти, как раз и ОО-подход пригодится, как вариант:
- В начале метода создаем объект класс Heap, передаем в него ссылку на массив
- В конце метода затираем у Heap ссылку на массив

Или как-нибудь по-другому (например ,чтобы не нужно было создавать объект при каждом вызове метода)

2021-09-29 17:43 UTC, molo4evan commented on Task_1_1_1/src/test/java/HeapTest.java
> +    public void TestOrdered () {
1. Не стоит хардкодить отсортированную версию, сделай отсортированную копию стандартными средствами Java (см. класс `Arrays`)
2. Тесты максимально однотимные, можно заменить 1 parameterized тестом (см. гайд в ссылках на gist)
3. А если null вместо массива передадим?
4. Название метода с маленькой буквы, это Java, а не C#

2021-09-30 17:54 UTC, MZolot commented
Проект точно Gradle. 
Переписала алгоритм без выделения дополнительной памяти, назвала нормально переменные и методы. Тесты переписала, но не разобралась, к сожалению, как их сделать параметризованными.

2021-10-01 04:55 UTC, molo4evan commented
> Проект точно Gradle. 

А где тогда файлы gradle?) Если они подсвечены красным в идее - значит они не добавлены в гит. Сделай на них git add (можно просто найти пункт в контекстном меню в идее) и закоммить.

2021-10-01 05:17 UTC, molo4evan commented on Task_1_1_1/src/main/java/nsu/oop/HeapSort.java
> +    private void swap (int[] arr, int n, int m) {
Не нужно вставлять пробел после имени функции. Для остальных мест также актуально.

2021-10-01 05:17 UTC, molo4evan commented on Task_1_1_1/src/main/java/nsu/oop/HeapSort.java
> +            return;
Нужно не просто `return`, а добавить адекватную обработку (кинуть исключение, например, `IllegalArgumentException`)

2021-10-01 05:17 UTC, molo4evan commented on Task_1_1_1/src/test/java/nsu/oop/HeapSortTest.java
> +        hs.sort(null);
`assertThrows` (с учетом коммента по коду)

2021-10-01 05:17 UTC, molo4evan commented on Task_1_1_1/src/test/java/HeapTest.java
> +    public void TestOrdered () {
Что именно не получилось с parameterized?

2021-10-08 05:10 UTC, merged